--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DavyCraft648/Oceanite
build-by-default: true
branches:
- master
projects:
  Oceanite:
    path: ""
    lint:
      phpstan: false
...
