name: Oceanite
main: DavyCraft648\Oceanite\Main
src-namespace-prefix: DavyCraft648\Oceanite
version: 1.1.0
api: [ "4.16.0" ]
depend:
  - Customies

authors:
  - DavyCraft648
description: Upgrade your Diamond tools and armor with Oceanite material!
website: https://github.com/DavyCraft648/Oceanite
